# Generated by Django 4.0.5 on 2022-06-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0004_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
